### ISSUE TITLE
form에서 이미지 필드가 비면 통과 못하는 이유

### ISSUE THREAD

**Issue by bella0413** [Animal-recipe/AnimalRecipe#13]
디폴트 이미지가 정해진 이미지 필드를 가진 모델이 있는데,
그 모델을 상속받은 폼에서 해당 이미지 필드의 값이 없으면 폼 제출이 안됩니다..
찾아봤는데 잘 모르겠네요...ㅠㅠ clean 함수에서 뭔가 다른 것을 해줘야 할까요............
넋두리이긴 한데 혹시 아시는 게 있다면 알려주세요,, @Hongji0611

**Comment by Hongji0611** [comment]
이미지를 하나의 formset으로하고, 갯수를 1개로 두시면 아마 될것 같습니다!

**Comment by bella0413** [comment]
조언해주셔서 감사합니다! 더 간단한 방법을 찾다가 장고 공식 문서 참고해서 forms.py 속 해당 필드에 
required=False를 줬더니 해결되었어요😭👍
근데 이게 또 어드민 페이지에서와 달리 실제 화면에서 실행해보면 안되길래,  템플릿에서 인풋 부분을
{{ form.filed }}로 하니까 되더라구요??
그래서 제가 그 {{ form.filed }}랑 형식 비슷하도록 템플릿의 인풋태그에 required=False를 별개로 추가했던 부분을 지워주니 
그제서야 잘 작동합니다.. forms.py에서 했는데 또 해줘서 그렇게 된건가??  
아무튼 잘 해결되었고 빈 폼 필드 값이더라도 실제 저장 시 디폴트 이미지가 잘 들어가있습니다.
기본이미지 또는 인풋으로 들어간 이미지 설정 부분 참고하시고 싶으시면 
User의 profile 필드와 register.html을 봐주시면 될 것 같습니다 😊
