### ISSUE TITLE
이슈 확인 부탁드립니다!

### ISSUE THREAD

**Issue by Hongji0611** [Animal-recipe/AnimalRecipe#31]
- 검색에서 레시피 또는 후기의 동물 종류가 모두인 경우, 카테고리에서 모두, 고양이, 강아지, 다른 동물일 때 전부 나타나야 한다고 생각합니다 (종류가 모두인 레시피는 강아지, 고양이도 먹을 수 있는 음식이기 때문입니다!!)
-  이미지 없을 경우, 배경을 회색으로 하셨는데 테두리를 둥글게 설정해야합니다 ( 이미지가 있을 경우, 둥글기 때문에 통일하는 것이 좋을것 같습니다!)
- home에서 후기에 레시피 제목을 추가하셨는데, 그 제목의 길이가 길어서  ...을 출력하는 경우, 리스트의 크기가 맞지 않습니다. 
 제목 박스의 크기 수정 부탁드립니다!
- 질문 상세페이지에서 그림자가 잘린것이 몇개 있습니다. (ex - 답변수)
- 답변수가 아니라 디자인에서는 이미지(엄지 손가락)로 되어있습니다. 이미지로 변경 부탁드립니다~!
- 마이페이지의 나의 레시피, 저장한 레시피에서 동물 박스의 색이 노란색입니다. 변경 부탁드립니다!!
- 마이페이지에서 편집으로 레시피, 후기, 등등을 삭제할 때 모달로 다시한번 물어보는것은 추가할 계획이신지 궁금합니다
- 나의 후기는 편집버튼을 눌렀을 경우 삭제 이미지가 뜨지 않습니다
- 나의 정보에서 비밀번호 자릿수가 *으로 보이지 않습니다
- 나의 정보 수정하기에서 기존 정보들을 placeholder가 아닌 value로 넣어주세요!!

**Comment by bella0413** [comment]
1. 모든 동물은 다 뜨도록 변경했습니다!!
2. 수정했습니다.
3. 제목의 길이가 길어서 ...을 출력하는 경우 리스트의 크기가 맞지 않는다는 게 무슨 뜻인지 잘 모르겠습니다ㅠㅠ 특정 아이템의 레시피 제목이 길어도 각 리스트와 리스트 아이템의 크기는 모두 일정해요. 혹시 좀 더 상세히 말씀해주실 수 있으신가요??
4. 수정했습니다!
5. 답변수는 글자로 써있는것이 맞고 좋아요수는 이미지로 변경했습니다!
6. 앗 그러네요. recipe.css에 반영하여 모든 페이지에 적용했습니담!
7. 네 마이페이지에서는 삭제 모달을 넣지 않을 생각입니다. 디자이너 님과 이야기했을 때 모달 얘기도 없었고 마이페이지까지 들어와서 삭제하는 거라 넣지 않을 생각입니다
8. 아이코 이번에 이미지가 없는 경우를 수정하다가 실수로 삭제해버렸네요ㅠㅠ감사합니다!!
9. 예전에 PR에서 설명했듯이 유저 정보를 처음 만들 때, 유저 정보를 수정할 때 비밀번호 갯수를 세는 로직이 일어나기 때문에 이미 가입하고 쓰는 경우 정보 수정 전에는 보이지 않으실 겁니다. 
10. 디자인 상 placeholder로 들어가있어서 디자이너님께 물어보셔야 할 것 같습니다!!

꼼꼼한 피드백 정말 감사합니다!! 👍❤

**Comment by Hongji0611** [comment]
3. 두 이미지 모두 100%의 화면 크기입니다.
![image](https://user-images.githubusercontent.com/63103070/104097154-7b045c00-52df-11eb-98ac-cbe846a3476a.png)
이렇게 레시피 제목이 짧은 경우에는 후기 리스트들이 잘 보이는데
![image](https://user-images.githubusercontent.com/63103070/104096637-54debc00-52df-11eb-8886-5c09b8bd2491.png)
레시피 제목이 긴 경우에는 리스트들이 갑자기 확대되더라구요ㅠㅠ

10. 사용자가 닉네임만 바꾸고 싶은 경우에도 반려동물 이름이나 종류를 꼭 입력해야하더라고요! 그래서 레시피나 후기 수정처럼 기존 내용이 value로 들어가는게 어떨까 싶습니다!

고생하셨습니다~!

**Comment by bella0413** [comment]
3. 아하 저는 후기 아이템과 연결된 레시피의 제목이 긴 경우를 말씀하시는 줄 알았는데 후기 아이템의 제목을 의미하신거군요.
어쩐지 에러가 안나서 한참 생각했네용.. 제가 가운데 정렬을 맞추려고 css 수정한 것 때문에 그런 듯 하니 수정하겠습니다!!
다음에는 더 정확히 말씀해주시거나 이번처럼 이미지로 부탁드려요!! ㅠㅠ
4.  그럼 디자이너님께 물어보고 반영하겠습니닷!!

**Comment by bella0413** [comment]
3. 홈에 있는 `.recipe_title`이 `max-width`가 정해져있지 않은데 flex를 써서 가운데 정렬을 했더니, `.recipe_title`이 넘치는 걸 flex가 반영해서 이상하게 깨지던 것이었습니다!! 수정했고 기왕 한 김에 `.recipe_size`의 최소 크기도 정해서 더 예쁘게 반응형이 되도록 만들었습니담. 둘 다 고치고 나서 로컬에서 정상 작동 확인했습니다.
4. 사실 저도 value가 더 낫다고 생각해서 그냥 @Hongji0611 님이 말씀해주신대로 바꿨습니다ㅎㅎㅎㅎ 말씀해주셔서 감사해요!! 비밀번호는 확인절차상 필요할 것 같고 나머지는 전부 value로 바꿨습니다! 디자이너님은 제가 설득해볼게요..(소근소근)
피드백 정말 감사합니다 🙇‍♀️❤
